version: "3.8"
services:
  db:
    image: postgres:15.1
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  backend:
    build:
      context: ./api
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ENABLE_LOGGER: ${ENABLE_LOGGER}
      ENABLE_DATABASE_LOGGER: ${ENABLE_DATABASE_LOGGER}
      PORT: ${PORT}
      BASE_URL: ${BASE_URL}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      ISSUER_BASE_URL: ${ISSUER_BASE_URL}
      AUDIENCE: ${AUDIENCE}
      MAILER_HOST: ${MAILER_HOST}
      MAILER_PORT: ${MAILER_PORT}
      MAILER_USERNAME: ${MAILER_USERNAME}
      MAILER_PASSWORD: ${MAILER_PASSWORD}

  frontend:
    env_file:
      - .env
    build:
      context: ./web
      args:
        - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
        - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
        - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
        - VITE_BASE_URL=${VITE_BASE_URL}
    container_name: frontend
    ports:
      - "5010:80"
    depends_on:
      - backend

volumes:
  db_data:
  minio_data:
