version: "3.8"
services:
  db:
    image: postgres:15.1
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alinews
      POSTGRES_PASSWORD: L2bBvWt7Xo5Hhcmy
      POSTGRES_DB: alinews
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./api
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: alinews
      DB_USERNAME: alinews
      DB_PASSWORD: L2bBvWt7Xo5Hhcmy
      ENABLE_LOGGER: y
      ENABLE_DATABASE_LOGGER: n
      PORT: 5000

  frontend:
    build:
      context: ./web
    container_name: frontend
    ports:
      - "5010:80"
    depends_on:
      - backend

volumes:
  db_data:
